# Generated by Django 3.2.21 on 2024-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abouttitle', models.CharField(editable=False, max_length=255)),
                ('email', models.EmailField(editable=False, max_length=255)),
                ('Aboutmessage', models.TextField()),
            ],
        ),
    ]
