# Generated by Django 3.2.21 on 2024-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Abouttitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
