# Generated by Django 3.2.21 on 2024-01-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
